// Code Generated by Sidekick is for learning and experimentation purposes only.

using System;
using System.Linq;

namespace Extensions
{
    public static class QueryableExtensions
    {
        public static IQueryable<T> Paginate<T>(this IQueryable<T> query, int page, int pageSize)
        {
            try
            {
                if (page < 1 || pageSize < 1)
                {
                    throw new ArgumentException("Page and pageSize must be greater than zero.");
                }

                return query.Skip((page - 1) * pageSize).Take(pageSize);
            }
            catch (Exception ex)
            {
                // Log the exception (ex)
                throw new InvalidOperationException("An error occurred while paginating the query.", ex);
            }
        }
    }
}
